---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - hpa.yaml
  - image-policy.yaml
  - image-update-automation.yaml
  - service.yaml
  - service-account.yaml
  - virtual-service.yaml
# CAUTION: commonLabels cannot be mutated in a deployment after they are set, kubernetes + kutomize will apply them to metadata AND selector labels.
# The only way to modify, is to delete the 'deployment' and recreate
commonLabels:
  app: ts-sdk-api
labels:
  - pairs:
      owner: sdk
      repo: ts-immutable-sdk
    includeSelectors: false
    fields:
      - path: metadata/labels
        create: true
      - path: spec/template/metadata/labels
        create: true
        group: apps
        kind: Deployment
