---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
bases:
  - ../base
patchesStrategicMerge:
  - deployment.yaml
  - image-policy.yaml
  - image-update-automation.yaml
  - service-account.yaml
  - virtual-service.yaml
  - hpa.yaml
