---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ts-sdk-api
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::783421985614:role/eks-sandbox-irsa-ts-sdk-api-role"
    eks.amazonaws.com/sts-regional-endpoints: "true"
