name: Deploy api

on:
  push:
    branches:
      - main
      - ts-backend

# this is used by github OIDC to assume the admin role later on
permissions: # see this: https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
  id-token: write # This is required for requesting the JWT
  contents: write # This is required for actions/checkout
  packages: write # This is required for pushing to the container registry

env:
  AWS_REGION: us-east-2

jobs:
  dev_docker_build_push:
    uses: immutable/im-shared-github-actions/.github/workflows/docker-build-tag-push.yml@v1.0.0
    with:
      environment: sandbox
      url: "https://api.sandbox.immutable.com"
      dockerfile: "./api/Dockerfile"
      role-to-assume: "arn:aws:iam::783421985614:role/immutable-nonprod-docker-image-push"
      role-session-name: "hub-immutable-nonprod-docker-image-push"
      aws-region: "us-east-2"
    secrets:
      github-token: ${{ secrets.TS_IMMUTABLE_SDK_GITHUB_TOKEN }}
